language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -t samferd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true samferd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-309516619954"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
